name: Run Bot

on:
  schedule:
    - cron: "30 4 * * *"   # 10:00 AM IST
    - cron: "30 6 * * *"   # 12:00 PM IST
    - cron: "10 10 * * *"  # 3:40 PM IST
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python bot.py
        
